-
  version: 1.1.{build}
  os: Visual Studio 2015
  platform: Any CPU
  build:
    project: src/TestAppveyor.sln
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal

-
  branches:
    only:
      - master
  before_build:
  - nuget restore src/TestAppveyor.sln
  configuration: Release
  deploy:
    - provider: NuGet
      api_key:
        secure: OvKqqdbyuSUeACcmmoHgSyrt0hzH+2pUnH3GJl+hhdu7ucCQf8cYxQ+fkVhwrhz6
      skip_symbols: true
      artifact: /.*\.nupkg/

-
  branches:
    only:
      - /dev-.*/
  before_build:
  - nuget restore src/TestAppveyor.sln
  configuration: Debug

-
  artifacts:
    path: src\TestAppveyor.ClassLibrary\bin\$(configuration)
    name: Package DLL
